int _putchar()[Dchar c[C[[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[);
int _isupper(int c);
int _isdigit(int c);
int mul(int a, int b);
void print_numbers()[Dvoid);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void print_triangle(int size);
